# Import Statements

In [3]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split


from sklearn.model_selection import train_test_split, KFold, cross_val_score, cross_validate
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Task 1: Cleaning your data

## 1.

In [4]:
wine_df = pd.read_csv('winequality-red.csv')



wine_df.isna().sum().sort_values(ascending=False)

total sulfur dioxide    98
density                 76
pH                      76
free sulfur dioxide     71
chlorides               50
residual sugar          44
citric acid             44
volatile acidity        22
sulphates               21
fixed acidity            0
alcohol                  0
quality                  0
dtype: int64

In [5]:
wine_df['total sulfur dioxide'] = wine_df['total sulfur dioxide'].fillna(wine_df['total sulfur dioxide'].median())
wine_df['density'] = wine_df['density'].fillna(wine_df['density'].median())
wine_df['pH'] = wine_df['pH'].fillna(wine_df['pH'].median())
wine_df['free sulfur dioxide'] = wine_df['free sulfur dioxide'].fillna(wine_df['free sulfur dioxide'].median())
wine_df['residual sugar'] = wine_df['residual sugar'].fillna(wine_df['residual sugar'].median())
wine_df['chlorides'] = wine_df['chlorides'].fillna(wine_df['chlorides'].median())
wine_df['citric acid'] = wine_df['citric acid'].fillna(wine_df['citric acid'].median())
wine_df['volatile acidity'] = wine_df['volatile acidity'].fillna(wine_df['volatile acidity'].median())
wine_df['sulphates'] = wine_df['sulphates'].fillna(wine_df['sulphates'].median())

In [6]:

wine_df.isna().sum().sort_values(ascending=False)

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

## 2.

copied from cleaned.py

In [7]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split

##plt.style.use('seaborn-darkgrid')

# Note that Best Practices, in terms of order of steps were violated in this program, please fix that.

# # Data Acquisition (I broke the CSV on purpose)
wine_df = pd.read_csv('winequality-red.csv')
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(wine_df.head(3))

X = wine_df.drop('quality', axis=1).values
y = np.ravel(wine_df[['quality']])


## Based on the slides, best practice would be to split the data into training and testing sets before doing any EDA or cleaning.

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)



# # Cleanup

# # Exploratory Data Analysis
# with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    # print(wine_df.describe())
# sns.pairplot(wine_df, hue = 'quality', height = 3, palette="husl")
# sns.violinplot(data=wine_df, x='quality', y='alcohol')
sns.FacetGrid(wine_df, hue='quality', height=6).map(plt.scatter, 'alcohol', 'fixed acidity').add_legend()
plt.show()


# ### Distribution of wine quality (target variable)
plt.hist(wine_df['quality'], bins=6, edgecolor='black')
plt.xlabel('quality', fontsize=20)
plt.ylabel('count', fontsize=20)
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.show()

OSError: 'seaborn-darkgrid' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)

# Task 2: Scaling your data

## 1.

In [8]:
X = wine_df.drop(columns='quality')
y = wine_df['quality']



knn = KNeighborsClassifier(n_neighbors=5)

## 2.

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

## 3.

In [10]:
scl = StandardScaler()
X_train_scaled = scl.fit_transform(X_train)
X_test_scaled = scl.transform(X_test)

## 4.

In [11]:
scoring = ['accuracy', 'f1_weighted']